### ISSUE TITLE
glm/UMath better support

### ISSUE THREAD

**Issue by elect86** [jOOQ/jOOU#10]
Hi,

first of all, let me say it is a really cool project!

Second, we are working on a java glm [here](https://github.com/java-graphics/glm) and at the moment I am implementing all the unsigned types, Vec2ub, Vec2ui, and so on

I am really interested in jOOU and I was wondering if it'd be possible to facilitate my task by implementing additional methods such as min(uX, uY), max(uX, uY) in a, let's say, `UMath` class...

For info, I am currently implementing such a class, but it'd be cool I could move it inside jOOU :)

**Comment by lukaseder** [comment]
Thank you very much for your nice words and for your suggestion. That's an excellent idea, it makes perfect sense. We'd love to integrate your work into jOOU, so that other users can profit from it as well

**Comment by elect86** [comment]
Awesome, thanks Lucas! :)
