### ISSUE TITLE
Improved hashCode() and toString() implementation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOU#18]
The current implementation on e.g. `UByte.toString()` is:

```java
    @Override
    public String toString() {
        return Short.valueOf(value).toString();
    }
```

This produces an unnecessary allocation of a `java.lang.Short`, when instead, we could write

```java
    @Override
    public String toString() {
        return Short.toString(value);
    }
```

Other types are also affected.

Credits to @knutwannheden for discovering this.

**Comment by knutwannheden** [comment]
In the scope of this issue I will also fix the `hashCode()` methods which can be optimized in the exact same way.

**Comment by lukaseder** [comment]
Agreed

**Comment by knutwannheden** [comment]
Unfortunately only since Java 1.8, so not in `jOOU-java-6`.
